---
- name: Configure central / discovery instance
  hosts: central
  gather_facts: true
  become: true

  vars:
    dsc_password: "{{ lookup('env', 'ADMIN_PASSWORDS') }}"

  tasks:
    - name: Create filesystem
      community.general.filesystem:
        fstype: xfs
        dev: /dev/xvdb

    - name: Create discovery folder
      ansible.builtin.file:
        path: /var/discovery/server/volumes
        state: directory
        mode: '0755'

    - name: Mount filesystem
      ansible.posix.mount:
        path: /var/discovery/server/volumes
        src: /dev/xvdb
        fstype: xfs
        state: mounted

    - name: Create discovery subfolders
      ansible.builtin.file:
        path: /var/discovery/server/volumes/{{ item }}
        state: directory
        mode: '0755'
      loop:
        - data
        - log
        - sshkeys

    - name: Install dependencies
      ansible.builtin.package:
        name:
          - podman
          - toolbox
        state: present

    - name: Log in to registry.redhat.io container registry
      containers.podman.podman_login:
        username: "{{ lookup('env', 'REGISTRY_USER') }}"
        password: "{{ lookup('env', 'REGISTRY_PASS') }}"
        registry: registry.redhat.io

    - name: Create a podman pod
      containers.podman.podman_pod:
        name: discovery-pod
        state: started
        publish:
          - 9443:443

    - name: Create database container for Red Hat Discovery tool
      containers.podman.podman_container:
        name: dsc-db
        pod: discovery-pod
        image: registry.redhat.io/rhel8/postgresql-12:latest
        restart_policy: on-failure
        volume:
          - dsc-data:/var/lib/pgsql/data
        env:
          POSTGRESQL_USER: dsc
          POSTGRESQL_PASSWORD: "{{ dsc_password }}"
          POSTGRESQL_DATABASE: dsc-db
        state: started

    - name: Create database container for Red Hat Discovery tool
      containers.podman.podman_container:
        name: discovery
        pod: discovery-pod
        image: registry.redhat.io/discovery/discovery-server-rhel8:latest
        restart_policy: on-failure
        volume:
          - /var/discovery/server/volumes/data/:/var/data:z
          - /var/discovery/server/volumes/log/:/var/log:z
          - /var/discovery/server/volumes/sshkeys/:/sshkeys:z
        env:
          DJANGO_DEBUG: False
          NETWORK_CONNECT_JOB_TIMEOUT: 60
          NETWORK_INSPECT_JOB_TIMEOUT: 600
          PRODUCTION: True
          QPC_DBMS_HOST: localhost
          QPC_DBMS_PASSWORD: "{{ dsc_password }}"
          QPC_DBMS_USER: dsc
          QPC_DBMS_DATABASE: dsc-db
          QPC_SERVER_PASSWORD: "{{ dsc_password }}"
          QPC_SERVER_TIMEOUT: 120
          QPC_SERVER_USERNAME: admin
          QPC_SERVER_USER_EMAIL: admin@example.com
        state: started

    - name: Generate systemd unit file for the Discovery pod
      containers.podman.podman_generate_systemd:
        name: discovery-pod
        dest: /etc/systemd/system

    - name: Ensure Discovery pod is started and enabled
      ansible.builtin.systemd:
        name: pod-discovery-pod
        daemon_reload: true
        state: started
        enabled: true

    # TODO - checkout Discovery CLI: https://access.redhat.com/documentation/en-us/subscription_central/2023/html-single/installing_and_configuring_discovery/index#assembly-installing-command-line-interface-inst
