---
- name: Remove all EC2 instances from Red Hat Discovery demo
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    project_tag: rh-discovery-demo

  tasks:
    - name: Terminate all EC2 instances with {{ project_tag }} tag
      amazon.aws.ec2_instance:
        state: absent
        filters:
          "tag:project": "{{ project_tag }}"
